server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MarcelloTinoco/service-config-repository
          search-paths: '*'
          username: MarcelloTinoco
          password: tinoco2017
          
